/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface NewOrder {
  'id' : bigint,
  'service' : string,
  'owner' : [] | [Principal],
  'whatsapp' : string,
  'fullName' : string,
  'description' : string,
  'deliveryTime' : string,
  'fileUpload' : Uint8Array,
  'email' : string,
  'timestamp' : bigint,
  'budget' : string,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'adminLogin' : ActorMethod<
    [string, string],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'adminLogout' : ActorMethod<[string], { 'ok' : null } | { 'err' : string }>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createOrder' : ActorMethod<
    [string, string, string, string, string, Uint8Array, string, string],
    bigint
  >,
  'deleteOrderWithToken' : ActorMethod<
    [string, bigint],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'downloadFileWithToken' : ActorMethod<
    [string, bigint],
    { 'ok' : Uint8Array } |
      { 'err' : string }
  >,
  'getAllOrders' : ActorMethod<[], Array<NewOrder>>,
  'getAllOrdersWithToken' : ActorMethod<
    [string],
    { 'ok' : Array<NewOrder> } |
      { 'err' : string }
  >,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getOrder' : ActorMethod<[bigint], NewOrder>,
  'getOrderDetailWithToken' : ActorMethod<
    [string, bigint],
    { 'ok' : NewOrder } |
      { 'err' : string }
  >,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];