/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AdminAuthResult = { 'ok' : string } |
  { 'err' : string };
export interface AppContent {
  'metaDescription' : string,
  'tiktok' : string,
  'metaKeywords' : string,
  'mail' : string,
  'whatsapp' : string,
  'description' : string,
  'facebook' : string,
  'address' : string,
  'titleTag' : string,
  'telegram' : string,
}
export interface ContactInfo {
  'email' : string,
  'address' : string,
  'phone' : string,
}
export interface FileData {
  'fileData' : string,
  'fileName' : string,
  'fileType' : string,
}
export interface Order {
  'id' : bigint,
  'total' : bigint,
  'userId' : Principal,
  'isPaid' : boolean,
  'products' : Array<OrderedProduct>,
}
export interface OrderedProduct { 'productId' : bigint, 'quantity' : bigint }
export interface Product {
  'id' : bigint,
  'files' : Array<FileData>,
  'name' : string,
  'description' : string,
  'price' : bigint,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addProduct' : ActorMethod<
    [string, bigint, string, Array<FileData>],
    Product
  >,
  'adminExists' : ActorMethod<[], boolean>,
  'adminLogin' : ActorMethod<[string, string], AdminAuthResult>,
  'adminLogout' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createDefaultAdmin' : ActorMethod<[], boolean>,
  'createOrder' : ActorMethod<[Array<OrderedProduct>], Order>,
  'deleteOrderWithToken' : ActorMethod<[string, bigint], undefined>,
  'downloadFileWithToken' : ActorMethod<[string, bigint], FileData>,
  'getAllOrdersWithToken' : ActorMethod<[string], Array<Order>>,
  'getAppContent' : ActorMethod<[], AppContent>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getContactInfo' : ActorMethod<[], ContactInfo>,
  'getMyOrders' : ActorMethod<[], Array<Order>>,
  'getOrderDetailWithToken' : ActorMethod<[string, bigint], Order>,
  'getProducts' : ActorMethod<[], Array<Product>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateAppContent' : ActorMethod<[AppContent], undefined>,
  'updateContactInfo' : ActorMethod<[ContactInfo], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];